package com.tosmart.dlna.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tosmart.dlna.data.local.DlnaItemEntity;

import com.tosmart.dlna.greendao.DlnaItemEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dlnaItemEntityDaoConfig;

    private final DlnaItemEntityDao dlnaItemEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dlnaItemEntityDaoConfig = daoConfigMap.get(DlnaItemEntityDao.class).clone();
        dlnaItemEntityDaoConfig.initIdentityScope(type);

        dlnaItemEntityDao = new DlnaItemEntityDao(dlnaItemEntityDaoConfig, this);

        registerDao(DlnaItemEntity.class, dlnaItemEntityDao);
    }
    
    public void clear() {
        dlnaItemEntityDaoConfig.clearIdentityScope();
    }

    public DlnaItemEntityDao getDlnaItemEntityDao() {
        return dlnaItemEntityDao;
    }

}
